config/routes.rb
Rails.application.routes.draw do 
  
  resources :chats
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: 'store#index'
  #get 'admin' => 'admin#index'

  
  controller :sessions do 
    get 'login' => :new
    post 'login' =>  :create
    delete 'logout' =>  :destroy
  end
  
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  post 'carts/hide_cart'



  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index' , as: 'store_index', via: :all 
  end
end

  # Creating sotre index to be Root URL for website, The latter tells Rails to create store_index_path and store_index_url accessor methods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # We need to operate on a member of the collection (individual product) as opposed to the entire collection which means all products

app/models/order.rb
require 'active_model/serializers/xml'
require 'pago'

class Order < ApplicationRecord
    include ActiveModel::Serializers::Xml
    enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
    }
    belongs_to :user
    has_many :line_items, dependent: :destroy
    validates :name, :address, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys

    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end


    def charge!(pay_type_params)
        payment_details = {}
        payment_method = nil 

        case pay_type
            when "Check"
                payment_method = :check
                payment_details[:routing] = pay_type_params[:routing_number]
                payment_details[:account] = pay_type_params[:account_number]
            when "Credit card"
                payment_method = :credit_card
                month,year = pay_type_params[:expiration_date].split(//)
                payment_details[:cc_num] = pay_type_params[:credit_card_number]
                payment_details[:expiration_month] = month
                payment_details[:expiration_year] = year
            when "Purchase order"
                payment_method = :po
                payment_details[:po_num] = pay_type_params[:po_number]
            end

        payment_result = Pago.make_payment(
            order_id: id,
            payment_method: payment_method,
            payment_details: payment_details
        )

        if payment_result.succeeded?
            OrderMailer.received(self).deliver_later
        else
            raise payment_result.error
        end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_action :authenticate_user!
  
  #skip_before_action :authorize, only: [:new, :create]
  
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :ensure_cart_isnt_empty, only: :new 
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user.id);
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @orders = Order.all
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.add_line_items_from_cart(@cart)
    @order.save

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil 
        ChargeOrderJob.perform_later(@order,pay_type_params.to_h)
        format.html { redirect_to store_index_url(locale: I18n.locale),
          notice: I18n.t('.thanks') }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end

    def pay_type_params
      if order_params[:pay_type] == "Credit Card"
        params.require(:order).permit(:credit_card_number, :expiration_date)
      elsif order_params[:pay_type] == "Check"
        params.require(:order).permit(:routing_number, :account_number)
      elsif order_params[:pay_type] == "Purchase Order"
        params.require(:order).permit(:po_number)
      else
    {}
    end end

    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to store_index_url, notice: 'Your cart is empty'
      end
    end

end

# def pay type params to submit the payment details to the customers back end 
# payment processing system.  

#understanding methods from reading rails guides 

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_with(model: order, local: true, id: 'detail') do |form|
  - if order.errors.any?
    #error_explanation
      %h2
        = raw t('errors.template.header', count: @order.errors.count, |
          model: t('activerecord.models.order'))                      |
        \.
      %p
        = t('errors.template.body')
      %ul
        - order.errors.full_messages.each do |message|
          %li= raw message
  .field
    = form.label :name, t('.name')
    = form.text_field :name, id: :order_name, size: 40
  .field
    = form.label :address, t('.address_html')
    = form.text_area :address, id: :order_address, rows: 3, cols: 40
  .field
    = form.label :email, t('.email')
    = form.text_field :email, id: :order_email, size: 40
  #pay-type-component
  .actions
    = form.submit t('.submit')

app/views/orders/edit.html.haml
%h1 Editing Order

= render 'form', order: @order 

= link_to 'Show', @order  
|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%p#notice= notice
%h1 Orders
%table

  %thead

    %tr
      %th Name
      %th Address
      %th Email
      %th Pay type
      %th{colspan: "3"}
  %tbody

    - @orders.each do |order|
      %tr
        %td= order.name
        %td= order.address
        %td= order.email
        %td= order.pay_type
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }
%br/

= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
%section.depot_form#depot_form
  %h1
    = t('.legend')
  / Translating Checkout
  = render 'form', order: @order
= javascript_pack_tag("pay_type")

app/views/orders/show.html.haml
%p#notice= notice 

%p 
  %strong Name: 
  = @order.name 

%p 
  %strong Address: 
  = @order.address 

%p 
  %strong Email: 
  = @order.email 

%p
%strong Pay type: 
= @order.pay_type

= link_to 'Edit', edit_order_path(@order) |
= link_to 'Back', orders_path 