config/routes.rb
Rails.application.routes.draw do 
  
  resources :chats
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: 'store#index'
  #get 'admin' => 'admin#index'

  
  controller :sessions do 
    get 'login' => :new
    post 'login' =>  :create
    delete 'logout' =>  :destroy
  end
  
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  post 'carts/hide_cart'



  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index' , as: 'store_index', via: :all 
  end
end

  # Creating sotre index to be Root URL for website, The latter tells Rails to create store_index_path and store_index_url accessor methods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # We need to operate on a member of the collection (individual product) as opposed to the entire collection which means all products

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.quantity += 1 
        else 
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price } 
    end
end

# smart add_product() method in our Cart, one that checks if our 
# list of items already includes the product we’re adding; if it does, it 
# bumps the quantity, and if it doesn’t, it builds a new LineItem:
# The find_by() method is a streamlined version of the where() method. 
# Instead of returning an array of results, it returns either an existing LineItem or nil.

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #before_action :authenticate_user!, only: [:create, :update, :destroy, :hide_cart]
  before_action :set_cart, only: [:show, :edit, :update, :destroy, :hide_cart]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart 

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, 
        notice: 'Your Carts empty!' }
      format.json { head :no_content }
    end
  end

  def hide_cart
    session[:hide_cart] ? session[:hide_cart] = false : session[:hide_cart] = true
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart' # Redirect to the catalog display by using the redirect_to()method. The :notice to send message 
    end                                                # Prevents user from retriggering error by clicking reloading button.
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
%article
  - if notice
    %aside#notice= notice
  %h2#cart_title
    = t('.title')
  #cart_button_hide
    = button_to ("Hide"), carts_hide_cart_path(id: @cart.id), remote: true
  %table
    = render(cart.line_items)
    %tfoot
      %tr
        %th{colspan: "2"} Total:
        %td.price= number_to_currency(cart.total_price)
  .actions
    #cart_button_empty
      = button_to t('.empty'), cart, method: :delete, data: { confirm: 'Are you sure?' }
    #cart_button_checkout
      = button_to ('Checkout'), new_order_path(locale: I18n.locale), method: :get, class: "checkout"

app/views/carts/_cart_hidden.html.haml
%article 
  = button_to ("Show Cart"), carts_hide_cart_path(id: @cart.id), remote: true

app/views/carts/_form.html.haml
= form_with(model: cart, local: true ) do |form|
  - if cart.errors.any?
    #error_explanation
      %h2
        = pluralize(cart.errors.count, "error")
        prohibited this cart from bieng saved: 

        %ul
          - cart.errors.full_messages.each do |message|
            %li = message
.actions 
  = form.submit

app/views/carts/edit.html.haml
%h1 Editing Cart 
  = render 'form', cart: @cart
  = link_to 'Show', @cart
  = link_to 'Back'. carts_path 

app/views/carts/index.html.haml
%p#notice= notice
%h1 Carts

%table
  %thead
    %tr
      %th{colspan: "3"}
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1
  = render 'form', cart: @cart
  = link_to 'Back', carts_path

app/views/carts/show.html.haml
= render @cart 